### ISSUE TITLE
Unhandled Exception - Nil Value - Waypoints Lua

### ISSUE THREAD

**Issue by LazyJ** [minetest-technic/unified_inventory#14]
The same error has crashed our server twice in a row.

We are running Unified Inventory, 2014_06_14 release, Minetest engine, 2014_06_26 release.

From server log:

First crash - 

>PLAYER JOINED: oriol
>16:06:11: ACTION[ServerThread]: Player oriol moved too fast; resetting position
>16:06:12: ERROR[main]: ERROR: An unhandled exception occurred: ...d_inventory_2014_06_24/unified_inventory/datastorage.lua:31: attempt to index local 'container' (a nil value)
>16:06:12: ERROR[main]: stack traceback:
>16:06:12: ERROR[main]: 	...d_inventory_2014_06_24/unified_inventory/datastorage.lua:31: in function 'get_container'
>16:06:12: ERROR[main]: 	...ied_inventory_2014_06_24/unified_inventory/waypoints.lua:203: in function <...ied_inventory_2014_06_24/unified_inventory/waypoints.lua:202>
>16:06:12: ERROR[main]: 	...minetest/minetest-0.4.9/bin/../builtin/game/register.lua:348: in function <...minetest/minetest-0.4.9/bin/../builtin/game/register.lua:336>

Second crash - 

>PLAYER JOINED: oriol
>17:42:25: ACTION[ServerThread]: Player oriol moved too fast; resetting position
>17:42:26: ERROR[main]: ERROR: An unhandled exception occurred: ...d_inventory_2014_06_24/unified_inventory/datastorage.lua:31: attempt to index local 'container' (a nil value)
>17:42:26: ERROR[main]: stack traceback:
>17:42:26: ERROR[main]: 	...d_inventory_2014_06_24/unified_inventory/datastorage.lua:31: in function 'get_container'
>17:42:26: ERROR[main]: 	...ied_inventory_2014_06_24/unified_inventory/waypoints.lua:203: in function <...ied_inventory_2014_06_24/unified_inventory/waypoints.lua:202>
>17:42:26: ERROR[main]: 	...minetest/minetest-0.4.9/bin/../builtin/game/register.lua:348: in function <...minetest/minetest-0.4.9/bin/../builtin/game/register.lua:336>

Of other note, thank you for such an incredibly useful mod. Among other things, Minetest is a resource-oriented game. Unified Inventory addresses the player's need to effectively manage their accumulated resources; a vital component of Minetest's game-play .

Thanks ;)

**Update**
After some more digging into this problem I found that the player's datastorage file had been corrupted (completely empty file). This is similar to what used to happen with player files resulting in a "playersArgsEnd not found" server crash.

I've also found that if the datastorage_!registered_players.data is ever fubared, everyone loses their waypoints.

Is there a way to handle the corrupted player datastorage files like Mintest now does with the "player" files?

For now I've created a script to backup these files just like I used to have to do for the "player" files.

Also, would it be possible to have Unified Inventory put these files in their own directory since there will be so many of them?

Thanks ;)

**Comment by VanessaE** [comment]
Is this still an issue?

**Comment by LazyJ** [comment]
@VanessaE  - I don't know. I have been unwilling to try waypoints again since they caused so much problems the first time for so little gain.

**Comment by VanessaE** [comment]
Well let's just close this for now since I could swear I'd fixed the last of waypoints' crashes.  If it happens again, we can re-open it.
