### ISSUE TITLE
WARNING: Undeclared global variable "creative_inventory" accessed at ...e/minetest/Server/bin/../mods/unified_inventory/init.lua:35

### ISSUE THREAD

**Issue by Megaf** [minetest-technic/unified_inventory#18]
Hi, Now Minetest server is actually exposing some bugs in mods and here is one on unified_inventory
```
07:51:41: WARNING: Undeclared global variable "creative_inventory" accessed at ...e/minetest/Server/bin/../mods/unified_inventory/init.lua:35
```
http://paste.debian.net/plain/132623

**Comment by Megaf** [comment]
Hi @t4im, you could join #Minetest-Dev on irc.freenode.net to talk about this issue.

**Comment by t4im** [comment]
see minetest/minetest#2236
