### ISSUE TITLE
WARNING: Undeclared global variable "intllib" accessed at /home/minetest/Server/bin/../mods/unified_inventory/

### ISSUE THREAD

**Issue by Megaf** [minetest-technic/unified_inventory#19]
Hi, Now Minetest server is actually exposing some bugs in mods and here is one on unified_inventory
```
07:51:41: WARNING: Undeclared global variable "intllib" accessed at /home/minetest/Server/bin/../mods/unified_inventory/api.lua:2
07:51:41: WARNING: Undeclared global variable "intllib" accessed at ...netest/Server/bin/../mods/unified_inventory/internal.lua:2
07:51:41: WARNING: Undeclared global variable "intllib" accessed at ...netest/Server/bin/../mods/unified_inventory/register.lua:2
07:51:41: WARNING: Undeclared global variable "intllib" accessed at ...e/minetest/Server/bin/../mods/unified_inventory/bags.lua:7
```
http://paste.debian.net/plain/132623

**Comment by VanessaE** [comment]
Actually in this case it's because unified inventory's support for intllib is just outdated. The current intllib API doesn't require this check anymore:  https://github.com/kaeza/minetest-intllib/blob/master/README.txt

**Comment by t4im** [comment]
Seems the support itself is the same. Just the way of checking for the dependency got more coupled onto a specific mod to supress the warnings.
Isn't this actually worse? It adds unnecessary calls compared to plain valid lua and takes away any option for a drop-in replacement of intlib without creating a nameclash.
And all this to silence a warning? :/
