### ISSUE TITLE
Feature Request - A Trash Can Slot and A Trash All Button for Each Bag

### ISSUE THREAD

**Issue by LazyJ** [minetest-technic/unified_inventory#29]
Our players have suggested having a trash can slot and a trash botton for each bag. Bags are often used to stash materials that may or may not be of use. When a project is completed, it would be nice to be able to dump all the unwanted scraps in the bags with a button click or to be able to drag individual, unwanted items into a trash slot.

**Comment by VanessaE** [comment]
Sorry for the late reply to this.  It seems like a good idea.  Pull requests welcome :)

**Comment by LazyJ** [comment]
The idea is beyond my coding skill at this time so no PR from me.

**Comment by kaeza** [comment]
:+1: from me.

If nobody's tackling it at the moment, I'd like to give it a try.

**Comment by kaeza** [comment]
How is this?

![screenshot_20161008_065621](https://cloud.githubusercontent.com/assets/2388420/19212287/6f6055aa-8d24-11e6-92bc-7279c51653e2.jpg)

**Comment by kaeza** [comment]
https://github.com/minetest-technic/unified_inventory/commit/75a0e6a31880bb3b0412288e7add99257805e8d1
