### ISSUE TITLE
Have the search field not be active by default when inventory is opened

### ISSUE THREAD

**Issue by veikk0** [minetest-technic/unified_inventory#31]
Currently when the player opens their inventory the item search field is active by default, which can be inconvenient if the player just wants to quickly check the status of their inventory. Usually one can open and close their inventory fairly quickly, since pressing the inventory key while the inventory is open closes it, but since the search field is active when the inventory is opened one either has to click anywhere in the inventory to deactivate the search field or close the inventory with the escape key.

**Comment by VanessaE** [comment]
This will break too many peoples' normal usage.  Normally it's open inventory -> immediately enter search phrase -> tab -> space (to trigger the "search" button).

If you don't focus on the search field by default, that adds extra steps:  Open inventory, mouse over to search field and click -> enter search phrase -> tab -> space.

It's trivial to open the inventory and tap Esc to close it; you can also just press Enter.
