### ISSUE TITLE
Improve trash!

### ISSUE THREAD

**Issue by HybridDog** [minetest-technic/unified_inventory#32]
l got the idea that the trash field could be replaced by a button which en-/disables trashing items when clicking on them. Currently putting items into the trash field is very annoying to me, l have to pull every single item there if l have full inventory and want to keep 2 of the items. lf there was this button instead, l would only need to left click it, then left click the unwanted items and after that left click the button again.

**Comment by Ferk** [comment]
> l have to pull every single item there if l have full inventory and want to keep 2 of the items.

I'm not sure if that's the case.. but if the crafting grid doesn't get trashed you could just place those 2 items in the crafting grid and press the "trash all inventory" button.

**Comment by VanessaE** [comment]
Ferk is correct in that the Crafting Grid is not affected by the "Trash all" button.  If you just need to keep a few things from your inventory and trash the rest, move those items into the Crafting Grid, then hit the Trash all button, and move them back.

**Comment by HybridDog** [comment]
l found another way: using the listring functionality in creative mode trash items by shift clicking them
it's really useful for me
