### ISSUE TITLE
my button has no border

### ISSUE THREAD

**Issue by cornernote** [minetest-technic/unified_inventory#35]
all the other buttons get a border, am I doing something wrong ?

```
unified_inventory.register_button('skyblock', {
	type = 'image',
	image = 'skyblock_quest.png',
	tooltip = 'Skyblock Missions',
	action = function(player)
		skyblock.feats.update(player:get_player_name())
	end,	
})
```

![image](https://cloud.githubusercontent.com/assets/51875/9084111/350b57b4-3baf-11e5-9b52-470b4a5b144a.png)

**Comment by VanessaE** [comment]
You just need to shrink the image down a bit - leave 20 or so pixels of space around it.

**Comment by RealBadAngel** [comment]
The button image shall be an icon on a transparent background.

**Comment by cornernote** [comment]
thanks!
