### ISSUE TITLE
Some refactoring to be be able to reuse the core api and opt-out default pages

### ISSUE THREAD

**Issue by Ferk** [minetest-technic/unified_inventory#41]
For [Dungeontest](https://forum.minetest.net/viewtopic.php?f=50&t=13317&sid=4f343a11e6e26a8b2a6559a1c1ea0425) I wanted to alter the version of unified_inventory that I'm using and add some stuff.
I was wondering if it's worth the trouble to clean it up, implement some things properly and submit a PR to this repo or if I should leave this as my own fork since maybe it's not useful for anybody else.

Things I'd like:

* When a page does not want to have the item list on the right side (ie.  "draw_item_list == false"), the size of the formspec should change to prevent having a huge empty space in there.

* I would like to add a better way to select, from minetest.conf, what buttons I would like to have. So, for example I should be able to completely prevent the bags.lua and related button/page from getting loaded at all, as well as the night/day buttons, the craftguide or even the default "craft". This way I could simply use the lightweight core of unified_inventory and add the pages I want just like I want them, when I want them (I still want to use a special page with draw_item_list that would only be shown in creative mode, for example).

* Probably the trash-all-inventory button should only be added in creative mode? Right now when not in creative the only thing it does when pressed is show a popup saying that it's disabled....

* An "unified_inventory_default_page" option that allows minetest.conf to set what page will be displayed by default.  Basically, this is just [changing this line](https://github.com/minetest-technic/unified_inventory/blob/9fe84789bad32f1e915d4a452347ce4021d87c2d/init.lua#L31):

         default = minetest.setting_get("unified_inventory_default_page") or "craft",

    Note that if the option is not set the default should still be "craft" and any mod that adds a page that could be set as default needs to test that it works, there could be a crash if the get_formspec of the mod that adds the page doesn't initialize stuff properly when the formspec loaded (which might happen before the on_join_player for that other mod gets called).. I have made the changes to the version of 3darmor mod that my game uses, for example.

If you think these changes don't make sense for your purposes, that's ok, I'll just maintain my own modified version of the mod.

**Comment by VanessaE** [comment]
Your ideas do sound good, except for changing the size of the formspec.  It should remain fixed-size ("lite" mode aside) for the sake of consistency.

**Comment by Ferk** [comment]
Hm. I could try to use the lite version for survival, but I'd still like the full version on creative.

Maybe the new feature you added regarding the full_inv override privilege would help, though. But I've had problems before trying to revoke priviledges to singleplayer, maybe in singleplayer full_inv is always on.

Are there any mods out there that actually use  draw_item_list = false ? I'd like to check them out and see how they actually handle the big empty space.

**Comment by VanessaE** [comment]
I'm not aware of any mods that use that feature, but I don't use that many inventory-hooked mods to begin with. :smile:

**Comment by 0-afflatus** [comment]
@Ferk your changes would benefit other games. At some point I intend to customise UI for [Grail Test](https://forum.minetest.net/viewtopic.php?f=50&t=10941). In general it would be good to hide buttons for players lacking privs to use them and where configurations have disable the related function.
