### ISSUE TITLE
Copy to craft grid: change behaviour of "all" button

### ISSUE THREAD

**Issue by lightonflux** [minetest-technic/unified_inventory#45]
When you have 93 mese and want to craft mese blocks then you can press the "all" button. But this copied all 93 mese in the grid. You get only 9 mese blocks and have 3 remaining in the grid. You then have to manually remove them. 

Change the behaviour so all does not mean all mese crystals, but the highest divider so you get all the possible blocks, but don't the remainder. 

So something like this

       copy ($total - $total % $amount-needed-by-recipe)

That way the user doesn't need to clear the craft grid all the time.

**Comment by VanessaE** [comment]
I don't think this is that big of a deal now with the advent of shift-click to move items to/from the crafting grid.
