### ISSUE TITLE
In creative mode, clicking buttons takes me to the ordinary creative formspec

### ISSUE THREAD

**Issue by raymoo** [minetest-technic/unified_inventory#51]
And then to "fix" it, I have to relog. Effectively I cannot use any of the buttons. It works fine in survival.

**Comment by MT-Modder** [comment]
Should be fixed by https://github.com/minetest-technic/unified_inventory/commit/f3127e9d7cba5e926e29e305669edfdfd6cd886e, at least it did for me.

**Comment by RealBadAngel** [comment]
fixed
