### ISSUE TITLE
Feature Request-duplicate recipe handling

### ISSUE THREAD

**Issue by deezl** [minetest-technic/unified_inventory#54]
I wish I was better at coding, I would maybe be able to just make a pull request for this. Trying to figure out a way to handle duplicate recipes without changing the recipes in individual mods. Is there a way to make UI check for such duplicate recipes (different mods using the same recipe, but with different outputs) and then be able to select the output? It would make it easier for server owners to update mods without having to stash changes and keep fixing the same recipes over and over. If this isn't possible, I understand, or if it would be just too complex or whatever, but I think a lot of people would appreciate such a feature. :)

**Comment by VanessaE** [comment]
It should be possible, but it would be complicated since you'd have to take shapeless recipes and item groups into account.  Better, I think, to yell at mod authors to clean up their duplicate recipes.

**Comment by Wuzzy2** [comment]
I agree with VanessaE here. Duplicate recipes are a mod / Minetest problem and is better fixed there. It's not worth fixing it in Unified Inventory IMO.
