### ISSUE TITLE
Release bags as seperate mod

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-technic/unified_inventory#74]
One of the things I dislike about UI is that it includes bags with no option to not include them.
While bags are certainly useful, they also heavily influence gameplay by making the inventory essentially much larger. This is a good reason for some people to _not_ want bags.

Therefore, I suggest to remove the bags from UI and instead release them as a seperate mod `ui_bags` which depends on UI. Bags are then only added when a player activates the new mod as well.

Do you agree?

**Comment by VanessaE** [comment]
Bags originally was a separate mod, the basic idea of which got merged into UI.  I believe it was based on https://forum.minetest.net/viewtopic.php?id=3081.  In any case, I disagree with the notion of "splitting" the bags into a separate mod.

On the other hand, making it require a privilege might be workable, then it could maybe be granted to trusted or "power" users who need it.

**Comment by Wuzzy2** [comment]
I am not happy with using privileges for every small feature, especially when it mostly involves gameplay. Especially for bags I think this is a very bad idea, this just clutters the privilege list for no reason and makes carrying bags useless if you don't have the priv, just adding pointless confusion. Bags should be enabled or disabled on a server-wide basis IMO.

It's not about “power users” at all. Its that bags make the gameplay MUCH easier by giving so many inventory slots. For creative games this of course doesn't matter, but for some games, this basically destroys difficulty by making inventory storage as easy as pie once you got all 4 large bags. Of course, I have nothing against bags, they are still a cool feature which are a legit extension to some subgames. I just don't think they should be added by default. UI adding bags for inventory extension is as if a crafting guide mod would automatically heal the player every second. It just seems a little bit out of scope. ;-)

My point is, even if bags are only meant as a convenience feature, they de facto HEAVILY alter gameplay which is IMO bad design, since UI conflates both gameplay and convenience features.

A possibility to not have bags should IMO be there and I think the easiest way to do this would be to use a different mod. I don't understand why you don't want this, since this seems like the most obvious solution for the problem. The reason why I suggest this is because for the user this makes it super easy to enable/disable them and they are only added after user explicit request.
One alternative to using a mod would be a config setting which IMO should be OFF by default because I think an inventory mod should not alter gameplay in such an extreme way (at least by default).

**Comment by VanessaE** [comment]
Frankly, I don't have any use for bags, myself.  However, this was RBA's mod, and I think it's important to try to keep it the way he would want it.

That said, simply replacing bags.lua with an empty file (e.g. `mv bags.lua bags.lua.tmp; touch bags.lua`) appears to be sufficient to do what you want.

**Comment by Wuzzy2** [comment]
I can't follow you. Are you now suggesting to dump bags altogether?

**Comment by VanessaE** [comment]
I'm suggesting that there seems to be very little support for your idea, so if someone doesn't want bags in their server/install, commands equivalent to the above will do the job, and still leave the possibility to easily reinstate the code.

**Comment by VanessaE** [comment]
they can be disabled now, e6c380d8c5c0451dd18402de642bcd8f9ad521db  (enabled by default)

**Comment by ShadowNinja** [comment]
@Wuzzy2 this seems to be more-or-less resolved, closing.
