### ISSUE TITLE
Possibility to disable "day", "night" and "give" buttons in singleplayer mode

### ISSUE THREAD

**Issue by bell07** [minetest-technic/unified_inventory#75]
As described above i like to see a possibility to disable the "day", "night" and "give" buttons in singleplayer survival. For multiplayer it is ok to enable the buttons depending on privileges, but in singleplayer mode the "give", "settime" and some other privileges are irrevokable so we need an other setting for them.  Maybe a new minetest.conf setting?

**Comment by Wuzzy2** [comment]
I prefer to have them disabled by default because an inventory mod should not interfere with gameplay.

But the real issue is that Minetest forces singleplayer privileges, this really should not be the case. https://github.com/minetest/minetest/issues/4413

**Comment by bell07** [comment]
Agree the privileges should not be irrevocable for single player. But it is not "my" issue. In singleplayer I do not need to disallow cheating for me self. I like cheats. But the cheats should be "hacky" and not regular gameplay functionality implemented as buttons in inventory screen. If I play survival the game experience is broken with unified inventory because the "giveme_1-99" buttons are very near to the "craft_1-99" buttons. The chance for wrong-clicks is high.
So my proposal is to disable all cheating buttons in unified inventory by default in non-creative mode to not touch the expected game experience.
I do not like all cheating buttons, my daughter do not need the giveme  buttons but like the set_day button. So it will be nice to have a user-configuration for the cheating buttons. In this configuration the permission check does sense if the user have permission for the cheat.
