### ISSUE TITLE
unified inventory not showing due to last minetest_game commit

### ISSUE THREAD

**Issue by JurajVajda** [minetest-technic/unified_inventory#85]
commit in minetest_game [d42ae715b8a4e5a46a590b0f97683855e5985cc1](https://github.com/minetest/minetest_game/commit/d42ae715b8a4e5a46a590b0f97683855e5985cc1)

the default minetest inventory is shown instead :/

**Comment by VanessaE** [comment]
Apply pull request #58 to fix this.  Also recommended, #86.

**Comment by JurajVajda** [comment]
great thanks, this worked ! :+1:
